import type { Employee } from "../types/employee";

export const EMPLOYEES:Employee[] = [
  {
    id: 1,
    name: "Oğuzhan Paytar",
    department: "Frontend",
    position: "Jr Frontend Developer",
    status: "Active",
    email: "oguzhan@example.com",
    phone: "+90 530 000 00 00",
    startDate: "2024-05-12",
  },
  {
    id: 2,
    name: "Elif Yılmaz",
    department: "HR",
    position: "HR Specialist",
    status: "Passive",
    email: "elif@example.com",
    phone: "+90 535 123 45 67",
    startDate: "2023-03-22",
  },
  {
    id: 3,
    name: "Ahmet Demir",
    department: "Backend",
    position: "Jr Backend Developer",
    status: "Passive",
    email: "ahmet@example.com",
    phone: "+90 532 456 78 90",
    startDate: "2022-11-10",
  },
  {
    id: 4,
    name: "Ayşe Kaya",
    department: "Design",
    position: "UI/UX Designer",
    status: "Active",
    email: "ayse@example.com",
    phone: "+90 531 987 65 43",
    startDate: "2021-08-15",
  },
  {
    id: 5,
    name: "Mehmet Yıldız",
    department: "Frontend",
    position: "Senior Frontend Developer",
    status: "Active",
    email: "mehmet@example.com",
    phone: "+90 530 222 33 44",
    startDate: "2023-02-05",
  },
];
